import type { Metadata } from "next";
import "./globals.css";
import dayjs from "dayjs";
import "dayjs/locale/ko";

dayjs.locale("ko");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HTMLLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <title>슬기로운 집사 생활</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
